name: PRCleanup Slides Stg
on:
  pull_request:
    types: [closed]
    paths:
      - 'slides/**'

jobs:
  delete-slides-stg:
    runs-on: 'ubuntu-latest'
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - 
        name: Install Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.21.2

      - name: Delete Tags on Quay
        id: delete_tags
        env:
          QUAYIO_API_TOKEN: '${{ secrets.QUAYIO_API_TOKEN }}'
        run: |
          curl -X DELETE -H "Authorization: Bearer ${QUAYIO_API_TOKEN}" https://quay.io/api/v1/repository/puzzle/ansible-training/tag/stg
